In [1]:
import pandas as pd
import numpy as np
import os

In [4]:
train = pd.DataFrame.from_csv('train.csv')

C:\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  """Entry point for launching an IPython kernel.

In [5]:
train.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
Id,,,,,,,,,,,,,,,,,,,,,
1,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,5
2,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,5
3,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,2
4,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,2
5,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,5

In [21]:
def five_num_summary(df, column):
    print(f'''
    Column: {column}
    Max value: {np.max(df[column])}
    Min value: {np.min(df[column])}
    Mean: {np.mean(df[column])}
    Median: {np.median(df[column])}
    ''')
for col_name in train.columns:
    five_num_summary(train, col_name)

    Column: Elevation
    Max value: 3849
    Min value: 1863
    Mean: 2749.3225529100528
    Median: 2752.0


    Column: Aspect
    Max value: 360
    Min value: 0
    Mean: 156.67665343915343
    Median: 126.0


    Column: Slope
    Max value: 52
    Min value: 0
    Mean: 16.501587301587303
    Median: 15.0


    Column: Horizontal_Distance_To_Hydrology
    Max value: 1343
    Min value: 0
    Mean: 227.19570105820105
    Median: 180.0


    Column: Vertical_Distance_To_Hydrology
    Max value: 554
    Min value: -146
    Mean: 51.076521164021166
    Median: 32.0


    Column: Horizontal_Distance_To_Roadways
    Max value: 6890
    Min value: 0
    Mean: 1714.0232142857142
    Median: 1316.0


    Column: Hillshade_9am
    Max value: 254
    Min value: 0
    Mean: 212.70429894179895
    Median: 220.0


    Column: Hillshade_Noon
    Max value: 254
    Min value: 99
    Mean: 218.96560846560845
    Median: 223.0


    Column: Hillshade_3pm
    Max value: 248
    Min value: 0
    Mean: 135.09199735449735
    Median: 138.0


    Column: Horizontal_Distance_To_Fire_Points
    Max value: 6993
    Min value: 0
    Mean: 1511.1472883597883
    Median: 1256.0


    Column: Wilderness_Area1
    Max value: 1
    Min value: 0
    Mean: 0.23789682539682538
    Median: 0.0


    Column: Wilderness_Area2
    Max value: 1
    Min value: 0
    Mean: 0.033002645502645506
    Median: 0.0


    Column: Wilderness_Area3
    Max value: 1
    Min value: 0
    Mean: 0.4199074074074074
    Median: 0.0


    Column: Wilderness_Area4
    Max value: 1
    Min value: 0
    Mean: 0.3091931216931217
    Median: 0.0


    Column: Soil_Type1
    Max value: 1
    Min value: 0
    Mean: 0.023478835978835978
    Median: 0.0


    Column: Soil_Type2
    Max value: 1
    Min value: 0
    Mean: 0.0412037037037037
    Median: 0.0


    Column: Soil_Type3
    Max value: 1
    Min value: 0
    Mean: 0.06362433862433862
    Median: 0.0


    Column: Soil_Type4
    Max value: 1
    Min value: 0
    Mean: 0.05575396825396826
    Median: 0.0


    Column: Soil_Type5
    Max value: 1
    Min value: 0
    Mean: 0.010912698412698412
    Median: 0.0


    Column: Soil_Type6
    Max value: 1
    Min value: 0
    Mean: 0.04298941798941799
    Median: 0.0


    Column: Soil_Type7
    Max value: 0
    Min value: 0
    Mean: 0.0
    Median: 0.0


    Column: Soil_Type8
    Max value: 1
    Min value: 0
    Mean: 6.613756613756614e-05
    Median: 0.0


    Column: Soil_Type9
    Max value: 1
    Min value: 0
    Mean: 0.0006613756613756613
    Median: 0.0


    Column: Soil_Type10
    Max value: 1
    Min value: 0
    Mean: 0.14166666666666666
    Median: 0.0


    Column: Soil_Type11
    Max value: 1
    Min value: 0
    Mean: 0.026851851851851852
    Median: 0.0


    Column: Soil_Type12
    Max value: 1
    Min value: 0
    Mean: 0.015013227513227513
    Median: 0.0


    Column: Soil_Type13
    Max value: 1
    Min value: 0
    Mean: 0.03148148148148148
    Median: 0.0


    Column: Soil_Type14
    Max value: 1
    Min value: 0
    Mean: 0.011177248677248678
    Median: 0.0


    Column: Soil_Type15
    Max value: 0
    Min value: 0
    Mean: 0.0
    Median: 0.0


    Column: Soil_Type16
    Max value: 1
    Min value: 0
    Mean: 0.00753968253968254
    Median: 0.0


    Column: Soil_Type17
    Max value: 1
    Min value: 0
    Mean: 0.04047619047619048
    Median: 0.0


    Column: Soil_Type18
    Max value: 1
    Min value: 0
    Mean: 0.003968253968253968
    Median: 0.0


    Column: Soil_Type19
    Max value: 1
    Min value: 0
    Mean: 0.0030423280423280425
    Median: 0.0


    Column: Soil_Type20
    Max value: 1
    Min value: 0
    Mean: 0.009193121693121692
    Median: 0.0


    Column: Soil_Type21
    Max value: 1
    Min value: 0
    Mean: 0.0010582010582010583
    Median: 0.0


    Column: Soil_Type22
    Max value: 1
    Min value: 0
    Mean: 0.022817460317460316
    Median: 0.0


    Column: Soil_Type23
    Max value: 1
    Min value: 0
    Mean: 0.050066137566137564
    Median: 0.0


    Column: Soil_Type24
    Max value: 1
    Min value: 0
    Mean: 0.016997354497354497
    Median: 0.0


    Column: Soil_Type25
    Max value: 1
    Min value: 0
    Mean: 6.613756613756614e-05
    Median: 0.0


    Column: Soil_Type26
    Max value: 1
    Min value: 0
    Mean: 0.0035714285714285713
    Median: 0.0


    Column: Soil_Type27
    Max value: 1
    Min value: 0
    Mean: 0.000992063492063492
    Median: 0.0


    Column: Soil_Type28
    Max value: 1
    Min value: 0
    Mean: 0.0005952380952380953
    Median: 0.0


    Column: Soil_Type29
    Max value: 1
    Min value: 0
    Mean: 0.08538359788359788
    Median: 0.0


    Column: Soil_Type30
    Max value: 1
    Min value: 0
    Mean: 0.04794973544973545
    Median: 0.0


    Column: Soil_Type31
    Max value: 1
    Min value: 0
    Mean: 0.021957671957671957
    Median: 0.0


    Column: Soil_Type32
    Max value: 1
    Min value: 0
    Mean: 0.04563492063492063
    Median: 0.0


    Column: Soil_Type33
    Max value: 1
    Min value: 0
    Mean: 0.040740740740740744
    Median: 0.0


    Column: Soil_Type34
    Max value: 1
    Min value: 0
    Mean: 0.001455026455026455
    Median: 0.0


    Column: Soil_Type35
    Max value: 1
    Min value: 0
    Mean: 0.006746031746031746
    Median: 0.0


    Column: Soil_Type36
    Max value: 1
    Min value: 0
    Mean: 0.0006613756613756613
    Median: 0.0


    Column: Soil_Type37
    Max value: 1
    Min value: 0
    Mean: 0.0022486772486772486
    Median: 0.0


    Column: Soil_Type38
    Max value: 1
    Min value: 0
    Mean: 0.04814814814814815
    Median: 0.0


    Column: Soil_Type39
    Max value: 1
    Min value: 0
    Mean: 0.04345238095238095
    Median: 0.0


    Column: Soil_Type40
    Max value: 1
    Min value: 0
    Mean: 0.030357142857142857
    Median: 0.0


    Column: Cover_Type
    Max value: 7
    Min value: 1
    Mean: 4.0
    Median: 4.0

In [20]:
train.columns

Index(['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology',
       'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways',
       'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm',
       'Horizontal_Distance_To_Fire_Points', 'Wilderness_Area1',
       'Wilderness_Area2', 'Wilderness_Area3', 'Wilderness_Area4',
       'Soil_Type1', 'Soil_Type2', 'Soil_Type3', 'Soil_Type4', 'Soil_Type5',
       'Soil_Type6', 'Soil_Type7', 'Soil_Type8', 'Soil_Type9', 'Soil_Type10',
       'Soil_Type11', 'Soil_Type12', 'Soil_Type13', 'Soil_Type14',
       'Soil_Type15', 'Soil_Type16', 'Soil_Type17', 'Soil_Type18',
       'Soil_Type19', 'Soil_Type20', 'Soil_Type21', 'Soil_Type22',
       'Soil_Type23', 'Soil_Type24', 'Soil_Type25', 'Soil_Type26',
       'Soil_Type27', 'Soil_Type28', 'Soil_Type29', 'Soil_Type30',
       'Soil_Type31', 'Soil_Type32', 'Soil_Type33', 'Soil_Type34',
       'Soil_Type35', 'Soil_Type36', 'Soil_Type37', 'Soil_Type38',
       'Soil_Type39', 'Soil_Type40', 'Cover_Type'],
      dtype='object')